### ISSUE TITLE
ChestDrop Error Itemstack

### ISSUE THREAD

**Issue by Luc8102** [samurainate/chestdrop#7]
Error:  http://pastebin.com/XwTCb7n7

Here is the config:

loreBasedGemModel: false
gem:
  Name: Hidden Gem
  Lore:
  - Found in special chests around the world.
worlds:
  world:
    enabled: false
    dropWhenEmpty: false
    maxRangeForDrops: 1000
    dropInterval: 1200
    dropChance: 0.1
  world_nether:
    enabled: false
    dropWhenEmpty: false
    maxRangeForDrops: 1000
    dropInterval: 1200
    dropChance: 0.1
  world_the_end:
    enabled: false
    dropWhenEmpty: false
    maxRangeForDrops: 1000
    dropInterval: 1200
    dropChance: 0.1
  Factions:
    enabled: false
    dropWhenEmpty: false
    maxRangeForDrops: 1000
    dropInterval: 1200
    dropChance: 0.1
  orgpvp:
    enabled: false
    dropWhenEmpty: false
    maxRangeForDrops: 1000
    dropInterval: 1200
    dropChance: 0.1
  mall:
    enabled: false
    dropWhenEmpty: false
    maxRangeForDrops: 1000
    dropInterval: 1200
    dropChance: 0.1
  Terrain:
    enabled: true
    dropWhenEmpty: false
    maxRangeForDrops: 500
    dropInterval: 15
    dropChance: 0.5
trades:
  exp:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: EXP_BOTTLE
      amount: 10
    cost: 1
  food:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: STEAK
      amount: 64
    cost: 1
  teleportation:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: ENDER_PEARL
      amount: 2
    cost: 1
  healing:
    item:
      ==: org.bukkit.inventory.ItemStack
      type: POTION_OF_HEALING
      amount: 5
    cost: 1

**Comment by samurainate** [comment]
Based on the stack trace, I think one of the item names in your config might not be a valid name.  Try removing items from the config and add them back one by one.

Nathaniel Meyer

**Comment by Luc8102** [comment]
WoW that was quick responce.

I deleted each trade one by one starting at the bottom up.  I deleted all the ones until I got to the default one exp.  So what was wrong?  and what does  ==: org.bukkit.inventory.ItemStack mean.  And how can I get item types for potions?

Thank You very much!

**Comment by samurainate** [comment]
Not sure why, going to have to look into it.  I haven't touched this in a while, and there are a lot of improvements needed.  At least I can handle failures like this more gracefully than a stack trace and die.

Nathaniel Meyer

**Comment by samurainate** [comment]
I tested with Spigot 1.8.8 and the git version (currently 1.0 alpha 6) and was able to successfully add a variety of potions using the in-game /addtrade command, and load the saved potions on server restart.   

The items in Config YML are serialized minecraft objects.  You can edit manually, but I wouldn't unless I knew exactly what I was doing.  That == line is the Java class, and then any class attributes are specified after.  Potions are tricky, they all have type POTION and use damage to specify the potion type.  The /addtrade command should populate config correctly with the item in hand while you are in game.  When setting up the server I would use creative mode to get the items I want for trades, and then /addtrade <gems> to handle the config.  Otherwise, the config file is a pain to edit manually.  /addtrade will also handle complex and custom items generated by other plugins (like crates). 

Regarding the null pointer exception, it looks like the Bukkit deserialize method logs that when it occurs, sometimes.  I've set it up to ignore bad trades with a warning like so

[08:19:37 WARN]: [ChestDrop] Failed to load trade 't1479993616538'.  Check your config, fix or remove this trade.
